# workflow name
name: release

# on events
on:
  push:

# jobs
jobs:

# generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:

      # step 1: checkout repository code inside the workspace directory of the runner
      - name: Checkout the repository
        uses: actions/checkout@v2

      # step 2: generate build files and dump inside the workspace directory of the runner
      - name: Generate build files
        uses: jrewienski/nrf52_build_github_action@master

      # step 3: Copy build-artifacts in the GitHub release
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./pca10059/mbr/armgcc/_build/*.hex"