# workflow name
name: release

# on events
on:
  push:

# jobs
jobs:

# generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:

  # step 1: checkout repository code inside the workspace directory of the runner
    name: Checkout the repository
    uses: actions/checkout@v2

  # step 2: generate build files and dump inside the workspace directory of the runner
    name: Generate build files
    uses: jrewienski/nrf52_build_github_action 